apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: juphc-tc-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
    - name: dockerconfig-ws

  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: main
    - name: app-name
      type: string

  tasks:
    - name: clone
      taskRef:
        name: clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: branch
          value: $(params.branch)
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: npminstall
      taskRef:
        name: npm
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: tests
      taskRef:
        name: jasmine
      runAfter:
        - npminstall
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
      params:
        - name: IMAGE
          value: "us.icr.io/$(context.pipelineRun.namespace)/$(params.app-name)"
